### ISSUE TITLE
`recommended_*` returns an `Array` and not an `ActiveRecord::Relation`

### ISSUE THREAD

**Issue by zenati** [davidcelis/recommendable#103] opened 2015-03-11 14:39 UTC
Hello,

```ruby
class User
  recommends :books
end
```

If a user has recommendations:
```
@user.recommended_books => [#<Book...>, #<Book...>, #<Book...>, ...]
```

if a user doesn't have recommendations:
```
@user.recommended_books =>  #<ActiveRecord::Relation []>
```

Am I missing something?

**Comment by zenati** [comment] 2015-03-11 14:40
Gemfile:
```
gem 'recommendable'
```
Gemfile.lock:
```
    recommendable (2.2.0)
      activesupport (>= 3.0.0)
      hooks (>= 0.2.1)
      redis (>= 2.2.0)
```

**Comment by mhuggins** [comment] 2015-03-11 15:58
Same issue as #96.

**Comment by davidcelis** [comment] 2015-03-11 18:20
Hey. I implemented a supposedly database-compatible way to do this in that above commit. Can you please try bundling off of master? I'd like to get this tested across several databases before releasing a new version.

**Comment by davidcelis** [comment] 2015-03-11 18:54
closing this as a duplicate of #96, actually. please comment there. thanks!

**Closed by davidcelis** 2015-03-11 18:54 UTC
